dist: trusty
sudo: false
language: node_js
node_js:
  - "12.13.1"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - cd ng-profile-builder-app
install:
  - npm i
  - npm i firebase-tools -g
script:
  - npm run lint
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run build
after_success:
  - echo "success deployed"
