dist: trusty
sudo: false
language: node_js
node_js:
  - "12.13.1"
addons:
  chrome: stable
before_install:
  - cd ng-profile-builder-app
install:
  - npm i
  - npm i firebase-tools -g
script:
  - npm run lint
  - npm run build --configuration=production
after_success:
  - echo "BUILD SUccessfull"
deploy:
  - echo "Deploying ........"
after_deploy:
  - echo "Deployed!"
